version: '3'
services:
  server:
    container_name: app-server
    build:
      context: .
      dockerfile: Dockerfile
    image: app-server:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
